#!/bin/bash
cd "$(dirname "$0")"
. common/libc.sh
if [[ $# < 1 ]]; then
  echo >&2 "Usage: $0 id [name1 [name2 ...]]"
  exit 2
fi
id=$1
shift 1
if [[ $# == 0 ]]; then
  names="__libc_start_main_ret system dup2 read write str_bin_sh"
else
  names="$@"
fi

ls -1 "db/${id}" >/dev/null 2>&1 || die "Invalid ID '$id'"
for name in $names; do
  found=0
  ls db/${id}/*.symbols | while read file; do
    offset=`cat $file | grep "^$name " | cut -d ' ' -f2`
	[ -z "$offset" ] && continue
	echo "offset_$name in " ${id::-7}.so = "0x${offset}"
	found=1
  done
  [ -z $found ] && die "No symbol $name found in libraries."
done

