#!/bin/bash
cd "$(dirname "$0")"
help() {
  echo >&2 "Usage: $0 path/to/libc.so"
  echo >&2 "    OR $0 bid=<BUILD_ID>"
  echo >&2 "    OR $0 md5=<MD5>"
  echo >&2 "    OR $0 sha1=<SHA1>"
  echo >&2 "    OR $0 sha256=<SHA256>"
  exit 2
}

if [[ $# != 1 ]]; then
  help
fi

arg="$1"

if [[ -f "$arg" ]]; then
  libc=$arg
  arg="sha1=$(sha1sum "$libc" | awk '{print $1}')"
fi

case "$arg" in
  bid=*)
    hash="${arg#"bid="}"
    file db/*.so | grep "=$hash," | perl -n -e '/db\/(.*)\.so:.*/&&print "id $1\n"'
    ;;
  md5=*)
    hash="${arg#"md5="}"
    md5sum db/*.so | grep "$hash " | perl -n -e '/db\/(.*)\.so/&&print "id $1\n"'
    ;;
  sha1=*)
    hash="${arg#"sha1="}"
    sha1sum db/*.so | grep "$hash " | perl -n -e '/db\/(.*)\.so/&&print "id $1\n"'
    ;;
  sha256=*)
    hash="${arg#"sha256="}"
    sha256sum db/*.so | grep "$hash " | perl -n -e '/db\/(.*)\.so/&&print "id $1\n"'
    ;;
  *)
    help
esac
