#!/bin/bash
if [[ $# != 1 ]]; then
  echo >&2 "Usage: $0 path/to/libc.so"
  exit 2
fi
libc=$1
sha1=`sha1sum $libc | awk '{print $1}'`
sha1sum db/*.so | grep "$sha1 " | perl -n -e '/db\/(.*)\.so/&&print "id $1\n"'
