#!/bin/sh
# More than inspired by https://www.redhat.com/archives/rpm-list/2003-June/msg00367.html

pkg=$1
if [ "$pkg" = "" ] || [ ! -e "$pkg" ]; then
    echo "no package supplied" 1>&2
   exit 1
fi

leadsize=96
o=$((leadsize + 8))
# shellcheck disable=SC2046
set $(od -j $o -N 8 -t u1 "$pkg")
il=$((256 * ( 256 * ( 256 * $2 + $3 ) + $4 ) + $5))
dl=$((256 * ( 256 * ( 256 * $6 + $7 ) + $8 ) + $9))

sigsize=$((8 + 16 * il + dl))
o=$((o + sigsize + ( 8 - ( sigsize % 8 ) ) % 8 + 8))
# shellcheck disable=SC2046
set $(od -j $o -N 8 -t u1 "$pkg")
il=$((256 * ( 256 * ( 256 * $2 + $3 ) + $4 ) + $5))
dl=$((256 * ( 256 * ( 256 * $6 + $7 ) + $8 ) + $9))

hdrsize=$((8 + 16 * il + dl))
o=$((o + hdrsize))

dd if="$pkg" ibs="$o" skip=1 2>/dev/null | gunzip 2>/dev/null || \
dd if="$pkg" ibs="$o" skip=1 2>/dev/null | unxz   2>/dev/null || \
dd if="$pkg" ibs="$o" skip=1 2>/dev/null | unzstd
